{{ config(materialized='table') }}

WITH CUSTOMERORDER AS (
    SELECT 
        C.CUSTOMERID, 
        CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME, 
        COUNT(O.ORDERID) AS ORDERCOUNT
    FROM SLEEKMART_OMS.L1_LANDING.CUSTOMERS C
    JOIN SLEEKMART_OMS.L1_LANDING.ORDERS O 
        ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY 
        C.CUSTOMERID, 
        C.FIRSTNAME,
        C.LASTNAME
    ORDER BY 
        ORDERCOUNT DESC
)

SELECT 
    CUSTOMERID, 
    CUSTOMERNAME, 
    ORDERCOUNT
FROM CUSTOMERORDER